### ISSUE TITLE
Fails with complaint about missing `.lock` file

### ISSUE THREAD

**Issue by andreasabel** [freckle/stack-cache-action#68]
E.g. https://github.com/andreasabel/miniagda/runs/6433623895?check_suite_focus=true
```
Error: ENOENT: no such file or directory, lstat 'stack-9.2.2.yaml.lock'
```
I am following the instructions given at https://tech.freckle.com/2021/05/18/haskell-on-actions/ : 
```
   - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@main
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
      - uses: freckle/stack-action@main
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
```
My repo does not contain the `stack.yaml.lock` files, I'd like them to be generated by the CI.  This is standard policy: one should not add generated files to version control.

Is there a way to use the cache action without a lock file in the repo?

Otherwise, the documentation should be extended to make this fact very clear.

I think there should be a step that generates the lock file if it is not present.  I think this could be done with stack's `--dry-run` option.
